# SPDX-FileCopyrightText: 2026 SmolBlackHole
#
# SPDX-License-Identifier: MPL-2.0

"""Initial engine schema. Frozen Alembic revision, including unchanged accounts."""

import sqlalchemy as sa
from alembic import op

revision = "engine_0001"
down_revision = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discord_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=False),
        sa.Column("profile_complete", sa.Boolean(), nullable=False),
        sa.Column("appearance", sa.JSON(), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
    )
    op.create_table(
        "artists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_source", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace", "external_id", name="uq_artists_provider_identity"
        ),
    )
    op.create_table(
        "listening_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("queue_revision", sa.Integer(), nullable=False),
        sa.Column("crossfade_seconds", sa.Integer(), nullable=False),
        sa.CheckConstraint("channel_id > 0", name="ck_session_channel"),
        sa.CheckConstraint(
            "crossfade_seconds IN (0,3,4,5,6,7)", name="ck_session_crossfade"
        ),
        sa.CheckConstraint(
            "queue_revision >= 0 AND revision >= queue_revision",
            name="ck_session_revisions",
        ),
        sa.CheckConstraint("volume >= 0 AND volume <= 1", name="ck_session_volume"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("state_hash", sa.String(), nullable=False),
        sa.Column("browser_hash", sa.String(), nullable=False),
        sa.Column("verifier", sa.String(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("state_hash"),
        sa.UniqueConstraint("browser_hash"),
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("uploader", sa.String(), nullable=True),
        sa.Column("uploader_url", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.CheckConstraint("duration_seconds >= 0", name="ck_tracks_duration"),
        sa.CheckConstraint("updated_at >= created_at", name="ck_tracks_timestamps"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace", "external_id", name="uq_tracks_media_identity"
        ),
    )
    op.create_table(
        "operation_receipts",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.JSON(), nullable=False),
        sa.Column("imported_outcome", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["listening_sessions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index(
        op.f("ix_operation_receipts_session_id"),
        "operation_receipts",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "playback_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("entry_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("end_reason", sa.String(), nullable=True),
        sa.Column("added_by", sa.JSON(), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.CheckConstraint(
            "(ended_at IS NULL AND end_reason IS NULL) OR (ended_at IS NOT NULL AND end_reason IS NOT NULL AND ended_at >= started_at AND end_reason IN ('completed', 'skipped', 'stopped', 'failed'))",
            name="ck_playback_end",
        ),
        sa.CheckConstraint("origin IN ('manual', 'radio')", name="ck_playback_origin"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["listening_sessions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "session_id", "entry_id", "track_id"),
    )
    op.create_index(
        op.f("ix_playback_records_track_id"),
        "playback_records",
        ["track_id"],
        unique=False,
    )
    op.create_index(
        "ix_playback_session_started",
        "playback_records",
        ["session_id", "started_at", "id"],
        unique=False,
    )
    op.create_table(
        "queue_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_by", sa.JSON(), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.CheckConstraint("origin IN ('manual', 'radio')", name="ck_queue_origin"),
        sa.CheckConstraint("position >= 0", name="ck_queue_position"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["listening_sessions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "position", name="uq_queue_session_position"),
    )
    op.create_index(
        op.f("ix_queue_entries_track_id"), "queue_entries", ["track_id"], unique=False
    )
    op.create_table(
        "queue_removals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("removal", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["listening_sessions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_queue_removals_expires_at"),
        "queue_removals",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_sessions_account_id"), "sessions", ["account_id"], unique=False
    )
    op.create_table(
        "track_artists",
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("position >= 0", name="ck_track_artist_position"),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("track_id", "artist_id"),
        sa.UniqueConstraint("track_id", "position", name="uq_track_artist_position"),
    )
    op.create_index(
        op.f("ix_track_artists_artist_id"), "track_artists", ["artist_id"], unique=False
    )
    op.create_table(
        "playback_checkpoints",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=True),
        sa.Column("entry_id", sa.Uuid(), nullable=True),
        sa.Column("play_id", sa.Uuid(), nullable=True),
        sa.Column("intent", sa.String(), nullable=False),
        sa.Column("position_seconds", sa.Float(), nullable=False),
        sa.Column("added_by", sa.JSON(), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.CheckConstraint(
            "(intent = 'stopped' AND entry_id IS NULL AND track_id IS NULL AND play_id IS NULL AND position_seconds = 0 AND added_by IS NULL AND origin = 'manual') OR (intent IN ('playing', 'paused') AND entry_id IS NOT NULL AND track_id IS NOT NULL)",
            name="ck_checkpoint_intent",
        ),
        sa.CheckConstraint(
            "origin IN ('manual', 'radio')", name="ck_checkpoint_origin"
        ),
        sa.CheckConstraint("position_seconds >= 0", name="ck_checkpoint_position"),
        sa.ForeignKeyConstraint(
            ["play_id", "session_id", "entry_id", "track_id"],
            [
                "playback_records.id",
                "playback_records.session_id",
                "playback_records.entry_id",
                "playback_records.track_id",
            ],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["listening_sessions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_playback_checkpoints_track_id"),
        "playback_checkpoints",
        ["track_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Engine data cannot be downgraded to the legacy core.")
