export const iconMaps = {
	lucide: {
		music: "i-lucide-music-2",
		radio: "i-lucide-radio-tower",
		headphones: "i-lucide-headphones",
		play: "i-lucide-play",
		pause: "i-lucide-pause",
		skip: "i-lucide-skip-forward",
		volume: "i-lucide-volume-2",
		// Standard keys (Nuxt UI)
		arrowDown: "i-lucide-arrow-down",
		arrowLeft: "i-lucide-arrow-left",
		arrowRight: "i-lucide-arrow-right",
		arrowUp: "i-lucide-arrow-up",
		caution: "i-lucide-circle-alert",
		check: "i-lucide-check",
		chevronDoubleLeft: "i-lucide-chevrons-left",
		chevronDoubleRight: "i-lucide-chevrons-right",
		chevronDown: "i-lucide-chevron-down",
		chevronLeft: "i-lucide-chevron-left",
		chevronRight: "i-lucide-chevron-right",
		chevronUp: "i-lucide-chevron-up",
		close: "i-lucide-x",
		copy: "i-lucide-copy",
		copyCheck: "i-lucide-copy-check",
		dark: "i-lucide-moon",
		drag: "i-lucide-grip-vertical",
		ellipsis: "i-lucide-ellipsis",
		error: "i-lucide-circle-x",
		external: "i-lucide-arrow-up-right",
		eye: "i-lucide-eye",
		eyeOff: "i-lucide-eye-off",
		file: "i-lucide-file",
		folder: "i-lucide-folder",
		folderOpen: "i-lucide-folder-open",
		hash: "i-lucide-hash",
		info: "i-lucide-info",
		light: "i-lucide-sun",
		loading: "i-lucide-loader",
		menu: "i-lucide-menu",
		minus: "i-lucide-minus",
		panelClose: "i-lucide-panel-left-close",
		panelOpen: "i-lucide-panel-left-open",
		plus: "i-lucide-plus",
		reload: "i-lucide-rotate-cw",
		search: "i-lucide-search",
		stop: "i-lucide-square",
		success: "i-lucide-circle-check",
		system: "i-lucide-monitor",
		tip: "i-lucide-lightbulb",
		upload: "i-lucide-upload",
		warning: "i-lucide-triangle-alert",
		// Custom keys (app-specific)
		chevronsUpDown: "i-lucide-chevrons-up-down",
		layoutDashboard: "i-lucide-layout-dashboard",
		list: "i-lucide-list",
		logOut: "i-lucide-log-out",
		paintbrush: "i-lucide-paintbrush",
		paintBucket: "i-lucide-paint-bucket",
		palette: "i-lucide-palette",
		settings: "i-lucide-settings",
		sparkles: "i-lucide-sparkles",
		sunMoon: "i-lucide-sun-moon",
		trash: "i-lucide-trash",
		type: "i-lucide-type",
		user: "i-lucide-user",
	},
	ph: {
		music: "i-ph-music-notes",
		radio: "i-ph-broadcast",
		headphones: "i-ph-headphones",
		play: "i-ph-play",
		pause: "i-ph-pause",
		skip: "i-ph-skip-forward",
		volume: "i-ph-speaker-high",
		// Standard keys (Nuxt UI)
		arrowDown: "i-ph-arrow-down",
		arrowLeft: "i-ph-arrow-left",
		arrowRight: "i-ph-arrow-right",
		arrowUp: "i-ph-arrow-up",
		caution: "i-ph-warning-circle",
		check: "i-ph-check",
		chevronDoubleLeft: "i-ph-caret-double-left",
		chevronDoubleRight: "i-ph-caret-double-right",
		chevronDown: "i-ph-caret-down",
		chevronLeft: "i-ph-caret-left",
		chevronRight: "i-ph-caret-right",
		chevronUp: "i-ph-caret-up",
		close: "i-ph-x",
		copy: "i-ph-copy",
		copyCheck: "i-ph-check-circle",
		dark: "i-ph-moon",
		drag: "i-ph-dots-six-vertical",
		ellipsis: "i-ph-dots-three",
		error: "i-ph-x-circle",
		external: "i-ph-arrow-up-right",
		eye: "i-ph-eye",
		eyeOff: "i-ph-eye-slash",
		file: "i-ph-file",
		folder: "i-ph-folder",
		folderOpen: "i-ph-folder-open",
		hash: "i-ph-hash",
		info: "i-ph-info",
		light: "i-ph-sun",
		loading: "i-ph-spinner",
		menu: "i-ph-list",
		minus: "i-ph-minus",
		panelClose: "i-ph-caret-left",
		panelOpen: "i-ph-caret-right",
		plus: "i-ph-plus",
		reload: "i-ph-arrow-clockwise",
		search: "i-ph-magnifying-glass",
		stop: "i-ph-square",
		success: "i-ph-check-circle",
		system: "i-ph-monitor",
		tip: "i-ph-lightbulb",
		upload: "i-ph-upload",
		warning: "i-ph-warning",
		// Custom keys (app-specific)
		chevronsUpDown: "i-ph-caret-up-down",
		layoutDashboard: "i-ph-layout",
		list: "i-ph-list",
		logOut: "i-ph-sign-out",
		paintbrush: "i-ph-paint-brush",
		paintBucket: "i-ph-paint-bucket",
		palette: "i-ph-palette",
		settings: "i-ph-gear-six",
		sparkles: "i-ph-sparkle",
		sunMoon: "i-ph-sun-dim",
		trash: "i-ph-trash",
		type: "i-ph-text-aa",
		user: "i-ph-user",
	},
	tabler: {
		music: "i-tabler-music",
		radio: "i-tabler-broadcast",
		headphones: "i-tabler-headphones",
		play: "i-tabler-player-play",
		pause: "i-tabler-player-pause",
		skip: "i-tabler-player-skip-forward",
		volume: "i-tabler-volume",
		// Standard keys (Nuxt UI)
		arrowDown: "i-tabler-arrow-down",
		arrowLeft: "i-tabler-arrow-left",
		arrowRight: "i-tabler-arrow-right",
		arrowUp: "i-tabler-arrow-up",
		caution: "i-tabler-alert-square-rounded",
		check: "i-tabler-check",
		chevronDoubleLeft: "i-tabler-chevrons-left",
		chevronDoubleRight: "i-tabler-chevrons-right",
		chevronDown: "i-tabler-chevron-down",
		chevronLeft: "i-tabler-chevron-left",
		chevronRight: "i-tabler-chevron-right",
		chevronUp: "i-tabler-chevron-up",
		close: "i-tabler-x",
		copy: "i-tabler-copy",
		copyCheck: "i-tabler-copy-check",
		dark: "i-tabler-moon",
		drag: "i-tabler-grip-vertical",
		ellipsis: "i-tabler-dots",
		error: "i-tabler-square-rounded-x",
		external: "i-tabler-external-link",
		eye: "i-tabler-eye",
		eyeOff: "i-tabler-eye-off",
		file: "i-tabler-file",
		folder: "i-tabler-folder",
		folderOpen: "i-tabler-folder-open",
		hash: "i-tabler-hash",
		info: "i-tabler-info-square-rounded",
		light: "i-tabler-sun",
		loading: "i-tabler-loader-2",
		menu: "i-tabler-menu",
		minus: "i-tabler-minus",
		panelClose: "i-tabler-layout-sidebar-left-collapse",
		panelOpen: "i-tabler-layout-sidebar-left-expand",
		plus: "i-tabler-plus",
		reload: "i-tabler-reload",
		search: "i-tabler-search",
		stop: "i-tabler-player-stop",
		success: "i-tabler-square-rounded-check",
		system: "i-tabler-device-desktop",
		tip: "i-tabler-bulb",
		upload: "i-tabler-upload",
		warning: "i-tabler-alert-triangle",
		// Custom keys (app-specific)
		chevronsUpDown: "i-tabler-arrows-up-down",
		layoutDashboard: "i-tabler-layout-dashboard",
		list: "i-tabler-list",
		logOut: "i-tabler-logout",
		paintbrush: "i-tabler-paint",
		paintBucket: "i-tabler-paint",
		palette: "i-tabler-palette",
		settings: "i-tabler-settings",
		sparkles: "i-tabler-sparkles",
		sunMoon: "i-tabler-sun-moon",
		trash: "i-tabler-trash",
		type: "i-tabler-typography",
		user: "i-tabler-user",
	},
	heroicons: {
		music: "i-heroicons-musical-note-20-solid",
		radio: "i-heroicons-signal-20-solid",
		headphones: "i-heroicons-speaker-wave-20-solid",
		play: "i-heroicons-play-20-solid",
		pause: "i-heroicons-pause-20-solid",
		skip: "i-heroicons-forward-20-solid",
		volume: "i-heroicons-speaker-wave-20-solid",
		// Standard keys (Nuxt UI)
		arrowDown: "i-heroicons-arrow-down-20-solid",
		arrowLeft: "i-heroicons-arrow-left-20-solid",
		arrowRight: "i-heroicons-arrow-right-20-solid",
		arrowUp: "i-heroicons-arrow-up-20-solid",
		caution: "i-heroicons-exclamation-triangle-20-solid",
		check: "i-heroicons-check-20-solid",
		chevronDoubleLeft: "i-heroicons-chevron-double-left-20-solid",
		chevronDoubleRight: "i-heroicons-chevron-double-right-20-solid",
		chevronDown: "i-heroicons-chevron-down-20-solid",
		chevronLeft: "i-heroicons-chevron-left-20-solid",
		chevronRight: "i-heroicons-chevron-right-20-solid",
		chevronUp: "i-heroicons-chevron-up-20-solid",
		close: "i-heroicons-x-mark-20-solid",
		copy: "i-heroicons-document-duplicate-20-solid",
		copyCheck: "i-heroicons-check-circle-20-solid",
		dark: "i-heroicons-moon-20-solid",
		drag: "i-heroicons-bars-3-20-solid",
		ellipsis: "i-heroicons-ellipsis-horizontal-20-solid",
		error: "i-heroicons-exclamation-circle-20-solid",
		external: "i-heroicons-arrow-top-right-on-square-20-solid",
		eye: "i-heroicons-eye-20-solid",
		eyeOff: "i-heroicons-eye-slash-20-solid",
		file: "i-heroicons-document-20-solid",
		folder: "i-heroicons-folder-20-solid",
		folderOpen: "i-heroicons-folder-open-20-solid",
		hash: "i-heroicons-hashtag-20-solid",
		info: "i-heroicons-information-circle-20-solid",
		light: "i-heroicons-sun-20-solid",
		loading: "i-heroicons-arrow-path-20-solid",
		menu: "i-heroicons-bars-3-20-solid",
		minus: "i-heroicons-minus-20-solid",
		panelClose: "i-heroicons-bars-3-bottom-left-20-solid",
		panelOpen: "i-heroicons-bars-3-20-solid",
		plus: "i-heroicons-plus-20-solid",
		reload: "i-heroicons-arrow-path-20-solid",
		search: "i-heroicons-magnifying-glass-20-solid",
		stop: "i-heroicons-stop-20-solid",
		success: "i-heroicons-check-circle-20-solid",
		system: "i-heroicons-computer-desktop-20-solid",
		tip: "i-heroicons-light-bulb-20-solid",
		upload: "i-heroicons-arrow-up-tray-20-solid",
		warning: "i-heroicons-exclamation-triangle-20-solid",
		// Custom keys (app-specific)
		chevronsUpDown: "i-heroicons-chevron-up-down-20-solid",
		layoutDashboard: "i-heroicons-squares-2x2-20-solid",
		list: "i-heroicons-list-bullet-20-solid",
		logOut: "i-heroicons-arrow-left-on-rectangle-20-solid",
		paintbrush: "i-heroicons-paint-brush-20-solid",
		paintBucket: "i-heroicons-paint-brush-20-solid",
		palette: "i-heroicons-swatch-20-solid",
		settings: "i-heroicons-cog-8-tooth-20-solid",
		sparkles: "i-heroicons-sparkles-20-solid",
		sunMoon: "i-heroicons-sun-20-solid",
		trash: "i-heroicons-trash-20-solid",
		type: "i-heroicons-language-20-solid",
		user: "i-heroicons-user-20-solid",
	},
} as const;

export type IconSet = keyof typeof iconMaps;

export type IconKey = keyof (typeof iconMaps)["lucide"];

export type IconMap = Record<IconKey, string>;

export const iconSets = Object.keys(iconMaps) as IconSet[];

export const iconItems = iconSets.map((s) => {
	let label: string;
	switch (s) {
		case "ph":
			label = "Phosphor";
			break;
		case "tabler":
			label = "Tabler";
			break;
		case "heroicons":
			label = "Heroicons";
			break;
		default:
			label = "Lucide";
	}

	return { label, value: s };
});
